### ISSUE TITLE
version 0.8.2 throws error when running in replica mode

### ISSUE THREAD

**Issue by mkhusro** [nats-io/nats-account-server#42]
trying out the replica mode for the nats-account-server and there seems to be an issue with 0.8.2 version
When starting the replica nats-account-server (0.8.2), it gives the following error

./go/bin/nats-account-server -c natsAccRepl.conf -DV -primary http://localhost:9090
2019/11/06 17:54:57.955890 [INF] loading configuration from "/Users/m0s00tx/natsAccRepl.conf"
2019/11/06 17:54:57.956159 [INF] starting NATS Account server, version 0.8.2
2019/11/06 17:54:57.956179 [INF] server time is Wed Nov  6 17:54:57 CST 2019
2019/11/06 17:54:57.956188 [INF] starting in replicated mode, with primary at http://localhost:9090
2019/11/06 17:54:57.956197 [INF] running in replicated mode without NATS notifications can result in delayed updates
2019/11/06 17:54:57.956201 [INF] loading operator from /Users/m0s00tx/nn/.nsc/nats/O/O.jwt
2019/11/06 17:54:57.957054 [INF] creating a store at /tmp/jwts
2019/11/06 17:54:57.957084 [INF] NATS is not configured, server will not fire notifications on update
2019/11/06 17:54:57.957091 [INF] grabbing initial JWT pack from primary http://localhost:9090
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1406d73]

goroutine 1 [running]:
github.com/nats-io/nats-account-server/server/core.(*AccountServer).initializeFromPrimary(0xc0000b2ea0, 0x0, 0x0)
    /Users/m0s00tx/go/src/github.com/nats-io/nats-account-server/server/core/server.go:449 +0x283
github.com/nats-io/nats-account-server/server/core.(*AccountServer).Start(0xc0000b2ea0, 0x0, 0x0)
    /Users/m0s00tx/go/src/github.com/nats-io/nats-account-server/server/core/server.go:233 +0x72f
main.main()
    /Users/m0s00tx/go/src/github.com/nats-io/nats-account-server/main.go:134 +0x855

Downgraded nats-account-server to 0.8.0, and everything runs as it should
Let me know if more details are required

**Comment by sasbury** [comment]
i see the issue, working on a test to prove the fix

**Comment by sasbury** [comment]
let me know if you see the issue again, but i think the problem was a silly log statement with an error that was nil and is fixed.
