### ISSUE TITLE
Run nats-account-server as Windows Service

### ISSUE THREAD

**Issue by LaurensVergote** [nats-io/nats-account-server#48]
nats-account-server can currently not be run as a Windows Service. Starting a nats-account-server as Windows Service currently gives the following error: 
Windows could not start the MyNAS service on Local Computer.
Error 1053: The service did not respond to the start or control request in a timely fashion.

We believe this to be because "ServiceMain" is not implemented in this project.
There are workarounds for this like [nssm](https://nssm.cc/) but it would be prefered this is not needed. nats-server can currently already run as a windows service and it would be nice if nats-account-server could as well.

**Comment by aricart** [comment]
Just verified, and indeed we are not implementing service for windows.
